name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: "0 18 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: be-a-guptaji  # <-- your GitHub username

      - name: Commit & Push SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/*.svg
          git commit -m "Update 3D Contribution Graph" || echo "No changes to commit"
          git push
